repos:

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: .*.drawio
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace

  # clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]

  # black
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
